### ISSUE TITLE
manque apostrophe dans le source EN :  cluster/po  R-fr.po  l 333

### ISSUE THREAD

**Issue by ChristianWia** [phgrosjean/rfrench#29]
Dans cluster/po  R-fr.po  en ligne 333, 

- msgid "no diss nor data found for clusplot()'"
- msgstr "pas de diss ni de données trouvées pour 'clusplot()'"

Verifier le source mais il doit manquer une apostrophe AVANT clusplot dans la version EN (je l'ai mise dans la version FR).

**Comment by phgrosjean** [comment]
Oui, il me semble aussi. La version française est donc correcte.

**Comment by ChristianWia** [comment]
ok, clusplot()'"   deviendra 'clusplot()'"  dans le source  et s'ils ne veulent pas, on reste propes.

**Comment by ChristianWia** [comment]
mailed to -> 
> maintainer("cluster")
[1] "Martin Maechler <maechler@stat.math.ethz.ch>"
because it is a package and not Core.

**Comment by mmaechler** [comment]
Thank, you are right.  However note that these need to be corrected in the package *source* code (R/*.R or src/*.c ...).
The *.pot files are automatically produce from the  package *source* files !
I've fixed in both (the source and *.pot) now  --> https://svn.r-project.org/R-packages/trunk/cluster/
(unfortunately, the `r-universe` does not track the `svn.r-project.org/R-packages/` even though several R __Recommended__ packages, notably `nlme`, `mgcv`and `cluster` are hosted there, also e.g., `XML` and `RCurl`.

**Comment by ChristianWia** [comment]
No problem and thanks. it is sometimes difficult for the translator to identify the authors when starting from a string to translate in a po file. But it is useful to accept that detection can also be done at this level.
